### ISSUE TITLE
Use dot notation for subcomponents

### ISSUE THREAD

**Issue by Kax675** [huntabyte/shadcn-svelte#116] opened 2023-06-19 19:52 UTC
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Svelte supports dot notation components like:

`<Header.Title />` with just basic index.js configuration.

Would be way better and easier to import components. For example we can turn;

This:

```
<script lang="ts">
  import { Alert, AlertDescription, AlertTitle } from "$components/ui/alert";
</script>

<Alert>
  <AlertTitle>Heads up!</AlertTitle>
  <AlertDescription>
    You can add components to your app using the cli.
  </AlertDescription>
</Alert>
```

To this:

```
<script lang="ts">
  import Alert from "$components/ui/alert";
</script>

<Alert>
  <Alert.Title>Heads up!</Alert.Title>
  <Alert.Description>
    You can add components to your app using the cli.
  </Alert.Description>
</Alert>
```

### What type of pull request would this be?

New Feature

### Provide relevant links or additional information.

https://svelte.dev/repl/96a0a6cb6308448c9eb6c01017650901?version=3.44.3

A repl example for this.

(sorry for editing spam)

**Comment by huntabyte** [comment] 2023-06-21 02:57
I think this is a good idea and I intend on doing so with the rip/replace of Radix Svelte -> MeltUI in the very near future.

**Comment by huntabyte** [comment] 2023-06-21 03:01
Closing this as just realizing it's a duplicate of #114

**Closed by huntabyte** 2023-06-21 03:01 UTC
Labels: type: feature
