### ISSUE TITLE
Install dependencies as devDependency

### ISSUE THREAD

**Issue by WarningImHack3r** [huntabyte/shadcn-svelte#625] opened 2024-01-09 19:42 UTC
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Svelte is a compiled language, thus no dependency is ever needed outside of dev as there is no runtime.

I can simply add `-D` (or `--save-dev` if you prefer) to the `add.ts` file to install required dependencies as `devDependency` instead of `dependency`.

I've been moving them manually for my projects using shadcn-svelte and I find it annoying to do so manually when there is no need to not install them as `devDependency` in the first place.

What do you think?

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

It's not especially mandatory as Vite [automatically discovers dependencies](https://github.com/vitejs/vite/discussions/1803) (source: [Reddit](https://www.reddit.com/r/sveltejs/comments/17jxpqj/sveltes_blurred_line_dependencies_vs/), but it's better to have all dependencies together under dev instead of having only shadcn-svelte (and other libs CLIs doing the same thing) putting its deps under `dependencies`.

**Comment by huntabyte** [comment] 2024-01-09 21:08
Duplicate of #580

**Closed by huntabyte** 2024-01-09 21:08 UTC
Labels: type: feature
