### ISSUE TITLE
Add new Input OTP component 

### ISSUE THREAD

**Issue by bigmitch19** [huntabyte/shadcn-svelte#1027] opened 2024-04-17 11:45 UTC
### Describe the feature

In the original shadcn library there is an [Input OTP](https://ui.shadcn.com/docs/components/input-otp) component. Can this be ported to this version?

**Comment by huntabyte** [comment] 2024-04-17 14:20
Please search issues before opening new ones, thank you!

Duplicate of #995

**Closed by huntabyte** 2024-04-17 14:20 UTC
Labels: type: feature
