### ISSUE TITLE
Input type not propagated to native input

### ISSUE THREAD

**Issue by SenneVanderAuwera** [huntabyte/shadcn-svelte#687] opened 2024-01-23 10:58 UTC
### Describe the bug

When setting the type of an input to "number" and then binding the value it will result in a string being assigned instead of a number.

### Reproduction

https://stackblitz.com/edit/github-xrre8u?file=src%2Froutes%2F%2Bpage.svelte

### System Info

```bash
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 10.56 GB / 15.57 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.14.1 - ~/.nvm/versions/node/v20.9.0/bin/pnpm
    bun: 1.0.2 - ~/.bun/bin/bun
npmPackages:
    @sveltejs/kit: ^2.3.2 => 2.3.2 
    bits-ui: ^0.14.0 => 0.14.0 
    formsnap: ^0.4.2 => 0.4.2 
    svelte: ^4.2.8 => 4.2.8 
    sveltekit-superforms: ^1.13.3 => 1.13.3
```

### Severity

annoyance

**Comment by tmadge** [comment] 2024-01-23 15:37
duplicate of #312 and #146 

if you're looking for a workaround for zod, check out #574

**Comment by SenneVanderAuwera** [comment] 2024-01-23 21:05
I saw that solution but in my case i'm not using zod so that's not a solution. I have fixed it by just converting the string to a number in a later stage of my process but it would be useful to be able to just bind the value. I have also figured out that [this seems to be svelte expected behaviour](https://stackoverflow.com/a/57393751).

#146 Proposed a solution but is hacky as they mention.

**Comment by huntabyte** [comment] 2024-01-24 02:13
Yeah this is expected behavior. If you want, you could create a separate `NumberInput` component.

**Closed by huntabyte** 2024-01-24 02:13 UTC
Labels: type: bug
