### ISSUE TITLE
'npx shadcn-svelte init' returns a dependency issue 

### ISSUE THREAD

**Issue by mastmagan007** [huntabyte/shadcn-svelte#128] opened 2023-06-25 22:28 UTC
### Change Type

Correction

### Proposed Changes

Error Log:
'Log files:
C:\Users\Taimoor\AppData\Local\npm-cache\_logs\2023-06-25T22_18_34_106Z-debug-0.log

# npm resolution error report

While resolving: my-app@0.0.1
Found: svelte@4.0.0
node_modules/svelte
  dev svelte@"^4.0.0" from the root project

Could not resolve dependency:
peer svelte@"^3.49.0" from lucide-svelte@0.252.0
node_modules/lucide-svelte
  lucide-svelte@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

**Comment by AdrianGonz97** [comment] 2023-06-25 22:49
Duplicate of #118.

We're planning on migrating away from `lucide-svelte` in favor of using `unplugin-icons` #119.

At a glance though, I don't see anything in `lucide-svelte` that would break in Svelte 4, so it's probably fine to continue using it for now. The only downside is that annoying error.

**Closed by AdrianGonz97** 2023-06-25 22:49 UTC
Labels: type: documentation
