### ISSUE TITLE
Implement OTP Input

### ISSUE THREAD

**Issue by TOTHT0MI** [huntabyte/shadcn-svelte#1128] opened 2024-06-08 19:07 UTC
### Describe the feature

Port [input-otp](https://ui.shadcn.com/docs/components/input-otp) to shadcn-svelte.

This component has been out for quite some time, but I've noticed, that the svelte port of shadcn does not have it currently.

**Comment by shyakadavis** [comment] 2024-06-08 19:26
Hello;

Related/duplicate of: https://github.com/huntabyte/shadcn-svelte/issues/1107

**Closed** 2024-06-10 17:08 UTC
Labels: type: feature
