### ISSUE TITLE
radix-svelte

### ISSUE THREAD

**Issue by mastmagan007** [huntabyte/shadcn-svelte#130] opened 2023-06-25 22:56 UTC
### Current Behavior

Error: Failed to resolve entry for package "radix-svelte". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "radix-svelte"

### Expected Behavior

It should get my accordion component working.

### Steps To Reproduce

npx shadcn-svelte add accordion
Then using code it displays error.

**Comment by huntabyte** [comment] 2023-06-26 00:01
Closing duplicate of #125

**Closed by huntabyte** 2023-06-26 00:01 UTC
Labels: type: bug
