### ISSUE TITLE
Sidebar takes a while to load

### ISSUE THREAD

**Issue by o-az** [huntabyte/shadcn-svelte#1376] opened 2024-10-28 00:28 UTC
### Describe the bug

I'm checking the `next` docs and noticed the sidebar takes a while to load even on subsequent visits:

https://github.com/user-attachments/assets/6d6cff02-ec22-417f-99b4-24998bf54267

### Reproduction

visit https://next.shadcn-svelte.com/docs/components/sidebar

### System Info

```bash
N/A
```

### Severity

annoyance

**Comment by huntabyte** [comment] 2024-10-28 01:14
I'm seeing about a fraction of that time on my end. It's loading another page inside of an `iframe`, we'll see what we can do to speed it up a bit

**Comment by huntabyte** [comment] 2024-10-30 01:00
Is anyone else able to reproduce this taking 5-10 seconds to load? If not I'm going to close this issue as I'm unable to reproduce and we are in fact prerendering that page as well.

**Comment by khakers** [comment] 2024-10-30 01:36
The Sidebar page takes 4+ seconds to load on my end as well. It's noticeably much longer than on other pages.

**Comment by huntabyte** [comment] 2024-10-30 21:22
Does the same happen at https://ui.shadcn.com/docs/components/sidebar ?

**Comment by demetrius-mp** [comment] 2024-10-31 02:02
> Is anyone else able to reproduce this taking 5-10 seconds to load? If not I'm going to close this issue as I'm unable to reproduce and we are in fact prerendering that page as well.

On my end, https://ui.shadcn.com/docs/components/sidebar takes longer to load than https://next.shadcn-svelte.com/docs/components/sidebar

In fact, at `shadcn`, the iframe blinks one before fully loading, while `shadcn-svelte` takes no longer than 1 second to load.

**Comment by huntabyte** [comment] 2024-10-31 14:54
Going to close this for the time being as it appears to be heavily dependent on connection. We are prerendering all these pages and serving them via Cloudflare pages. If someone can identify a way we can improve the load times for everyone, I'll more than happily merge a PR!

**Closed by huntabyte** 2024-10-31 14:54 UTC
