### ISSUE TITLE
Page scroll disappear when clicking on select trigger but not choosing anything

### ISSUE THREAD

**Issue by phenomen** [huntabyte/shadcn-svelte#514] opened 2023-12-07 20:52 UTC
### Current Behavior

Page scrollbar disappears and you can't scroll the page anymore (with a mousewhell at least).

### Expected Behavior

Page scrollbar should reappear after dropdown is closed even if no option was selected.

### Steps To Reproduce

1. Click on the select trigger ("Select a fruit").
2. Click outside the dropdown to hide it (don't select an option).

### Link to Reproduction / Stackblitz ([reproduction template](https://shadcn-svelte.com/repro))

https://www.shadcn-svelte.com/docs/components/select

### More Information

I've noticed it in the Date Picker with Preset but it's reproducible with any Select.

**Comment by huntabyte** [comment] 2023-12-07 21:18
I'm not able to reproduce this:

https://github.com/huntabyte/shadcn-svelte/assets/64506580/ebbf801d-32f6-4b2b-b105-127fcf0664e1

**Comment by phenomen** [comment] 2023-12-07 21:20
@huntabyte can you try here? (Date Picker with Preset)

https://www.shadcn-svelte.com/docs/components/date-picker#with-presets

**Comment by huntabyte** [comment] 2023-12-07 23:22
I can in fact reproduce, this is in fact a bug and I'm looking into it!

**Comment by huntabyte** [comment] 2023-12-08 01:19
Opened a PR to have it resolved with Melt UI and then I'll patch bits and we'll be good to go here!

https://github.com/melt-ui/melt-ui/pull/809

**Comment by huntabyte** [comment] 2023-12-11 16:11
Update to bits-ui@0.11.7 for this to be fixed!

**Closed by huntabyte** 2023-12-11 16:11 UTC
Labels: type: bug
