### ISSUE TITLE
Adding the `loop` prop to `<Command.Dialog>` gives a `<Dialog> was created with unknown prop 'loop'` warning in the console

### ISSUE THREAD

**Issue by r3Fuze** [huntabyte/shadcn-svelte#757] opened 2024-02-10 14:40 UTC
### Describe the bug

Adding the `loop` prop to `<Command.Dialog>` gives this warning in the browser console:

> \<Dialog> was created with unknown prop 'loop'

I believe this happens because `$$restProps` gets spread on both `<Dialog.Root>` and `<Command>`, but `loop` is not a valid prop for `<Dialog.Root>`: https://github.com/huntabyte/shadcn-svelte/blob/main/apps/www/src/lib/registry/default/ui/command/command-dialog.svelte#L13

The `cmdk-sv` package seems to have the same issue for the same reason: https://github.com/huntabyte/cmdk-sv/blob/main/src/lib/cmdk/components/CommandDialog.svelte#L63

I wasn't sure what repo to file this issue in, so I created a single issue here, but I've provided repoductions for both repos.

Everything works as expected functionality wise, but it would be nice not having the warning in the console.

### Reproduction

**shadcn-svelte:** https://stackblitz.com/edit/github-5d2zkj?file=src%2Froutes%2F%2Bpage.svelte
**cmdk-cv:** https://stackblitz.com/edit/vitejs-vite-i5wkeh?file=src%2FApp.svelte&terminal=dev

### Logs

```bash
<Dialog> was created with unknown prop 'loop'
```

### System Info

```bash
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 7800X3D 8-Core Processor
    Memory: 36.24 GB / 63.15 GB
  Binaries:
    Node: 20.11.0 - ~\AppData\Local\pnpm\node.EXE
    npm: 10.2.4 - ~\AppData\Local\pnpm\npm.CMD
    pnpm: 8.15.1 - ~\AppData\Local\Microsoft\WinGet\Links\pnpm.EXE
  Browsers:
    Edge: Chromium (121.0.2277.112)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/kit: ^2.5.0 => 2.5.0
    bits-ui: ^0.17.0 => 0.17.0
    cmdk-sv: ^0.0.13 => 0.0.13
    mode-watcher: ^0.2.0 => 0.2.0
    svelte: ^4.2.10 => 4.2.10
    sveltekit-superforms: 2.0.0-alpha.52 => 2.0.0-alpha.52
```

### Severity

annoyance

**Comment by huntabyte** [comment] 2024-02-10 18:54
Thanks for creating the reproductions. This is one of those annoying Svelte logs that make composition a pain because.

**Comment by huntabyte** [comment] 2024-03-11 04:19
I'm going to close this for now as this log only shows during dev and isn't a high enough priority for me to fix considering this problem will be solved with Svelte 5. :/

**Closed by huntabyte** 2024-03-11 04:19 UTC
Labels: type: annoyance
