### ISSUE TITLE
Dropdown does not open when triggered by a variable without a button click.

### ISSUE THREAD

**Issue by brunostjohn** [huntabyte/shadcn-svelte#685] opened 2024-01-22 16:50 UTC
### Describe the bug

The variable sets correctly. This applies to both stores and reactive variables.

### Reproduction

```svelte
<script lang="ts">
  import * as DropdownMenu from "$lib/components/ui/dropdown-menu";
  import * as Button from "$lib/components/ui/button";

  let open = false;

  const handleKeyDown = (event: KeyboardEvent) => {
    if (event.metaKey && event.key === "y") {
      event.preventDefault();
      open = !open;
    }
  };
</script>

<svelte:window on:keydown={handleKeyDown} />

<DropdownMenu.Root bind:open>
  <DropdownMenu.Trigger asChild let:builder={builderDropDown}>
    <Tooltip.Root>
      <Tooltip.Trigger asChild let:builder={builderTooltip}>
        <Button
          variant="ghost"
          builders={[builderDropDown, builderTooltip]}
          class={cn("relative ml-2 h-8 w-8 rounded-full", $$props.class)}
        >
          I'm a button!
      </Tooltip.Trigger>
      <Tooltip.Content>
         Cool hover tooltip
      </Tooltip.Content>
    </Tooltip.Root>
  </DropdownMenu.Trigger>
  <DropdownMenu.Content>
    Some context-adding stuff
  </DropdownMenu.Content>
</DropdownMenu.Root>
```

### System Info

```bash
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 88.75 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - /usr/local/bin/node
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.13.1 - /usr/local/bin/pnpm
    bun: 1.0.20 - ~/.bun/bin/bun
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 120.1.61.120
    Safari: 17.2.1
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.0.6 
    formsnap: ^0.4.2 => 0.4.2 
    mode-watcher: ^0.1.2 => 0.1.2 
    svelte: ^4.2.7 => 4.2.7 
    sveltekit-superforms: ^1.13.1 => 1.13.1 
```
```


### Severity

annoyance

**Comment by brunostjohn** [comment] 2024-01-22 16:50
As a sidenote, thank you for the work you're doing on this library, it's really a joy to use!

**Comment by brunostjohn** [comment] 2024-01-22 16:57
For more context, it works after the first button press. Here's my ultra jank solution:

```ts
  onMount(() => {
    const btn = document.getElementsByClassName("user-menu-btn")[0] as HTMLButtonElement | undefined;
    btn?.click();
    open = true;
    open = false;
    btn?.blur();
    document.body.focus();
  });
```

**Comment by huntabyte** [comment] 2024-01-22 18:19
Does the same happen if you put the dropdown builder after the tooltip builder in the `Button` builders array?

**Comment by brocococonut** [comment] 2024-01-24 02:00
@brunostjohn I can't seem to find the issue you're mentioning.. I did notice a few missing imports and an unterminated `<Button>` tag, so I've corrected them below. I've removed the `metaKey` requirement as it's not getting activated at all with it on my computer (likely a misconfiguration on my end), but loading it up and hitting just the `y` key that it's been modified to do activates the dropdown as expected.

```svelte
<script lang="ts">
  import * as DropdownMenu from "$lib/components/ui/dropdown-menu";
  import * as Tooltip from "$lib/components/ui/tooltip";
  import { Button } from "$lib/components/ui/button";
  import { cn } from "$lib/utils";

  let open = false;

  const handleKeyDown = (event: KeyboardEvent) => {
    if (event.key === "y") {
      event.preventDefault();
      open = !open;
    }
  };
</script>

<svelte:window on:keydown={handleKeyDown} />

<DropdownMenu.Root bind:open>
  <DropdownMenu.Trigger asChild let:builder={builderDropDown}>
    <Tooltip.Root>
      <Tooltip.Trigger asChild let:builder={builderTooltip}>
        <Button variant="destructive" builders={[builderDropDown, builderTooltip]} class={cn("", $$props.class)}>
          I'm a button!
        </Button>
      </Tooltip.Trigger>
      <Tooltip.Content>Cool hover tooltip</Tooltip.Content>
    </Tooltip.Root>
  </DropdownMenu.Trigger>
  <DropdownMenu.Content>Some context-adding stuff</DropdownMenu.Content>
</DropdownMenu.Root>
```

Keep in mind, whenever the context menu shows up and I haven't hit the button, that's me hitting the `y` key. There's a page refresh between each time as well just to be sure.

[Screencast from 2024-01-24 12-58-09.webm](https://github.com/huntabyte/shadcn-svelte/assets/6368283/796e87f6-7a7c-4976-811e-92eead0fc472)

**Comment by huntabyte** [comment] 2024-01-24 02:19
`metaKey` is `cmd` on mac! I'll try to reproduce when I get the chance as well to confirm, but if you have any additional context @brunostjohn it'd be appreciated!

**Comment by brocococonut** [comment] 2024-01-24 02:33
> `metaKey` is `cmd` on mac! I'll try to reproduce when I get the chance as well to confirm, but if you have any additional context @brunostjohn it'd be appreciated!

I can publish my code as an example repo if you'd like!
Saves you having to set up all the boilerplate.

**Comment by huntabyte** [comment] 2024-01-25 23:59
Closing as I'm not able to reproduce this issue running the latest versions of all packages. I'm using a Mac and have created a working version of the code you dropped here: https://stackblitz.com/edit/github-we1qm7?file=src%2Froutes%2F%2Bpage.svelte

**Closed by huntabyte** 2024-01-25 23:59 UTC
Labels: type: bug
