### ISSUE TITLE
Using Popover + Select (preventScroll) -> Date Picker with Presets Example

### ISSUE THREAD

**Issue by roostad** [huntabyte/shadcn-svelte#531] opened 2023-12-10 15:29 UTC
### Current Behavior

When using Select (preventScroll set to true by default) inside a Popover (preventScroll set to false by default), there is an issue where overflow remains hidden if you click the Select component followed by clicking outside the area of the Popover component (no selection).

This is just a quick note for an adjustment on this in the Date Picker with Presets example: https://www.shadcn-svelte.com/docs/components/date-picker#with-presets

### Expected Behavior

To re-enable scrolling after clicking outside the Popover with the Select menu open, preventScroll should also be set on Popover.Root.

```
<Popover.Root openFocus preventScroll>
    ...
</Popover.Root>
```

Pull request added: https://github.com/huntabyte/shadcn-svelte/pull/532

### Steps To Reproduce

See link to example below.

### Link to Reproduction / Stackblitz ([reproduction template](https://shadcn-svelte.com/repro))

https://www.shadcn-svelte.com/docs/components/date-picker#with-presets

**Comment by huntabyte** [comment] 2023-12-11 02:55
Duplicate of #514 - its a bug and will be fixed once I release a patch update to bits tomorrow

**Closed by huntabyte** 2023-12-11 02:55 UTC
Labels: type: bug
