### ISSUE TITLE
CLI should gracefully exit if no command is passed on `pnpx shadcn-svelte`

### ISSUE THREAD

**Issue by AdrianGonz97** [huntabyte/shadcn-svelte#27] opened 2023-05-29 12:55 UTC
Typically CLI's should just return the contents of `--help` (it already does in our case) without any errors

Current state: 
```zsh
Usage: shadcn-svelte [options] [command]

Add shadcn-svelte components to your project

Options:
  -v, --version        display the version number
  -h, --help           display help for command

Commands:
  init [options]       Configure your SvelteKit project.
  add [components...]  add components to your project
  help [command]       display help for command
 ERROR  Command failed with exit code 1: shadcn-svelte

pnpm: Command failed with exit code 1: shadcn-svelte
    at makeError (/home/koala/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:24242:17)
    at handlePromise (/home/koala/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:24813:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/home/koala/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:223404:7)
    at async /home/koala/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:232806:21
    at async main (/home/koala/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:232773:34)
    at async runPnpm (/home/koala/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:233028:5)
    at async /home/koala/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:233020:7
```

Edit: It seems like this only happens with `pnpx`

**Comment by ferntheplant** [comment] 2023-06-21 18:57
`pnpx` is [technically deprecated](https://web.archive.org/web/20230202163724/https://pnpm.io/6.x/pnpx-cli) but I confirmed this error occurs with `pnpm dlx` too. However this is likely a bug with pnpm since the same thing occurs with `pnpm dlx create-react-app` with no arguments. I'll file a bug on their end

**Comment by huntabyte** [comment] 2023-06-21 23:05
Thanks @ferntheplant ! @AdrianGonz97 good to close this issue considering it extends beyond our control?

**Comment by huntabyte** [comment] 2023-06-21 23:09
Thank you!

**Closed by huntabyte** 2023-06-21 23:09 UTC
Labels: type: bug, status: needs owner
