### ISSUE TITLE
Horizontal Scrolling not working on chrome desktop

### ISSUE THREAD

**Issue by neckaros** [huntabyte/shadcn-svelte#1101] opened 2024-05-18 10:51 UTC
### Describe the bug

On chrome for Windows [ 124.0.6367.208 (Build officiel) (64 bits) ] it is not possible to scroll horizontally on the exemple provided in the doc: No scroll bar is visible so unless you have a touchpad you can't scroll

![image](https://github.com/huntabyte/shadcn-svelte/assets/7789770/cecfa6a1-d3f6-42c1-a0ab-d79b204d2683)

I also reproduced in my own application

### Reproduction

https://stackblitz.com/edit/github-xeeapq?file=src%2Froutes%2F%2Bpage.svelte

### System Info

```bash
chrome for Windows [ 124.0.6367.208 (Build officiel) (64 bits) ]
```
Tried in incognito mode to make sure no extension is having side effect

Works on Safari on MacOS

### Severity

blocking all usage of shadcn-svelte

**Comment by Lakelimbo** [comment] 2024-05-19 18:58
Can't reproduce. Both on Chrome and Edge on Windows I can scroll horizontally with my mouse (holding shift + scrolling) on the docs example.
On your Stackblitz demo, however, for some reason it takes some seconds until I can scroll after the page is fully loaded. But on my end, on the docs, it's normal.

**Comment by neckaros** [comment] 2024-05-20 17:16
> Can't reproduce. Both on Chrome and Edge on Windows I can scroll horizontally with my mouse (holding shift + scrolling) on the docs example. On your Stackblitz demo, however, for some reason it takes some seconds until I can scroll after the page is fully loaded. But on my end, on the docs, it's normal.

Thanks for the reply. On windows we are expected to use shift + scroll only? Why is there no scrollbar like on Mac Safari?

**Comment by Lakelimbo** [comment] 2024-05-21 01:31
> > Can't reproduce. Both on Chrome and Edge on Windows I can scroll horizontally with my mouse (holding shift + scrolling) on the docs example. On your Stackblitz demo, however, for some reason it takes some seconds until I can scroll after the page is fully loaded. But on my end, on the docs, it's normal.
> 
> Thanks for the reply. On windows we are expected to use shift + scroll only? Why is there no scrollbar like on Mac Safari?
> 
> On Shadcn (non svelte) i do have the horizontal scrollbar: https://ui.shadcn.com/docs/components/scroll-area

There is for me. It only shows when you hover over the scroll area. On light mode it's light grey, so it might be a bit difficult to see at a glance:
![image](https://github.com/huntabyte/shadcn-svelte/assets/59345467/81a63084-10af-43f0-a8ea-2bc36529910e)

**Comment by GewoonJaap** [comment] 2024-05-26 15:36
I am having the same issue. Scrollbar isn't visible on my website and the bit-ui demo (https://www.bits-ui.com/docs/components/scroll-area). However it is visible on the shadcn website. If I copy paste the scroll area demo code from the shadcn website there is no scrollbar to be found :(

**Comment by GewoonJaap** [comment] 2024-05-26 15:37
![afbeelding](https://github.com/huntabyte/shadcn-svelte/assets/33700526/e9621f1c-42e3-4b47-8c55-855b0cb3164a)
![afbeelding](https://github.com/huntabyte/shadcn-svelte/assets/33700526/d53d676d-a4d1-474a-bf1c-2a87356221fa)

**Comment by GewoonJaap** [comment] 2024-05-26 15:49
When using devtools on firefox and enabling the repsonsive design modus and selecting a phone/tablet, then on hover I can see the scrollbar appearing, on desktop it stays invisible

**Comment by GewoonJaap** [comment] 2024-05-26 15:57
Found a workaround, open the `scroll-area-scrollbar.svelte`

Add these styles:
```css
	.visible {
		visibility: visible !important;
	}
	.visible > * {
		visibility: visible !important;
	}
```

Add the following class to both the thumb and scrollbar: `visible`

![afbeelding](https://github.com/huntabyte/shadcn-svelte/assets/33700526/fc264c57-7aa8-42da-a795-8174ce6259fc)
Now the thumb is always visible. (Somehow after using this hack the thumbs where visible again even without the style???)

**Comment by huntabyte** [comment] 2024-11-01 01:17
Fixed in `shadcn-svelte@next`

**Closed by huntabyte** 2024-11-01 01:17 UTC
