### ISSUE TITLE
CLI: add support for custom `ui` directory

### ISSUE THREAD

**Issue by MentalGear** [huntabyte/shadcn-svelte#841] opened 2024-03-01 14:26 UTC
### Describe the feature

This would align with `shadcn` cli option as of https://github.com/shadcn-ui/ui/pull/2266.

Use case: Need to label all shadcn components explicitly, e.g. as there might be issues with changes/updates.

**Comment by huntabyte** [comment] 2024-03-03 23:11
Duplicate of #547

**Closed by huntabyte** 2024-03-03 23:11 UTC
Labels: type: feature
