### ISSUE TITLE
RunTime Error after installing Form

### ISSUE THREAD

**Issue by amirbenasr** [huntabyte/shadcn-svelte#276] opened 2023-09-08 10:20 UTC
### Current Behavior

I was trying to implement Form in my sveltekit app.

But the runtime keeps on telling me that I Cannot find module '@/utils' which has been used in the form folder.

I had to change '@/utils' to '$lib/utils' to make it work

Errors :

Failed to load url @/utils (resolved id: @/utils) in C:/Users/Mecanique/Desktop/lazy-student-frontend/my-app/src/lib/components/ui/form/form-native-select.svelte. Does the file exist?

Error: Cannot find module '@/utils' imported from 'C:/Users/Mecanique/Desktop/lazy-student-frontend/my-app/src/lib/components/ui/form/form-item.svelte'

    at nodeImport (file:///C:/Users/Mecanique/Desktop/lazy-student-frontend/my-app/node_modules/.pnpm/vite@4.4.9_@types+node@20.5.9/node_modules/vite/dist/node/chunks/dep-df561101.js:56010:25)
    at ssrImport (file:///C:/Users/Mecanique/Desktop/lazy-student-frontend/my-app/node_modules/.pnpm/vite@4.4.9_@types+node@20.5.9/node_modules/vite/dist/node/chunks/dep-df561101.js:55912:30)
    at eval (C:/Users/Mecanique/Desktop/lazy-student-frontend/my-app/src/lib/components/ui/form/form-item.svelte:4:37)

### Expected Behavior

It should be installed normally as other components i believe so

### Steps To Reproduce

1.Using the form component
2. pnpm run dev

**Comment by tmadge** [comment] 2023-09-08 12:06
possible duplicate of #263

**Comment by huntabyte** [comment] 2023-09-08 16:02
Did you run `shadcn-svelte@latest add`? Pinging @AdrianGonz97 as I believe this issue was resolved by #263.

**Comment by AdrianGonz97** [comment] 2023-09-08 16:30
As @huntabyte said, please ensure that you're adding the `@latest` tag at the end of the command: `npx shadcn-svelte@latest add ...`. This will ensure that you're using the latest version of the CLI!

**Comment by mateusfl** [comment] 2023-09-08 18:42
> As @huntabyte said, please ensure that you're adding the `@latest` tag at the end of the command: `npx shadcn-svelte@latest add ...`. This will ensure that you're using the latest version of the CLI!

I just installed the form with the `@latest` tag and my aliases were not replaced as well.

**Comment by huntabyte** [comment] 2023-09-08 20:54
Interesting @mateusfl , will look into this later today!

**Closed** 2023-09-08 21:46 UTC
Labels: type: bug, status: under review
