### ISSUE TITLE
Support the new Tailwind v4 CSS config

### ISSUE THREAD

**Issue by TheOnlyTails** [huntabyte/shadcn-svelte#1529] opened 2024-12-01 20:16 UTC
### Prerequisites

- [X] This feature already exists in [shadcn/ui](https://github.com/shadcn/ui) - if not, it won't be considered here so don't continue with your issue.

### Describe the feature

Detect when the tailwindcss v4 beta is installed, and generate the config directly into `app.css`.
I've made an example of such config (that I use in my own app) here: https://gist.github.com/TheOnlyTails/2be83c37d96ed988c8d3353ec8574a75

This new config uses tailwind's new `--color-*` variables, plus the `light-dark()` function to handle theming and `@utility` to extend the `container` class.

**Comment by luxus** [comment] 2024-12-01 22:09
only update to beta and the app.css?

**Comment by huntabyte** [comment] 2024-12-03 00:21
When it is stable and ready - duplicate of #1527

**Closed by huntabyte** 2024-12-03 00:21 UTC
Labels: type: feature
