### ISSUE TITLE
<Combobox> doesn't use the Bits UI primitive

### ISSUE THREAD

**Issue by alvinometric** [huntabyte/shadcn-svelte#1269] opened 2024-09-13 10:58 UTC
### Prerequisites

- [X] This feature already exists in [shadcn/ui](https://github.com/shadcn/ui) - if not, it won't be considered here so don't continue with your issue.

### Describe the feature

More of a discussion point than a feature request, but Bits UI has a [combobox](https://www.bits-ui.com/docs/components/combobox) primitive, but `shadcn-svelte` doesn't use it.

Instead is built using a composition of the <Popover /> and the <Command /> components, just like the original shadcn/ui. 

It feels like a missed opportunity when Bits UI already has an amazing component.

**Comment by huntabyte** [comment] 2024-09-19 16:32
Duplicate of #917

**Closed by huntabyte** 2024-09-19 16:32 UTC
Labels: type: feature
